### PR TITLE
Update vas module 

### LINKED ISSUE #20: Announcer Broken
module announcer is broken , always announcer to world

### PR DESCRIPTION
**Pull request by milestorme**
Repair world announcer, added config option.

Closes #20

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Updated the comment in order to automatically close #20. Modified the code a little bit to move the changes further to the right so that they are in line with the function again. I also tested the changes, everything seems to be ok. Just waiting once more for the Travis run to complete and then this can be merged.

Thanks @milestorme for the new PR and for not giving up :+1:

**Comment by Stoabrogga** [comment]
Ok, Travis run was ok, merging this PR.

**Comment by BarbzYHOOL** [comment]
ty !!!

**Comment by milestorme** [comment]
I apologise for my frustration there’s no excuse  . thank you for being so patient with me and teaching me how to submit code better. Glad we got it fixed

**Comment by BarbzYHOOL** [comment]
no problem, git is very frustrating until it's mastered

**Pull request merged**
